repos:
  # -------------------------
  # General hygiene
  # -------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files

  # -------------------------
  # Markdown / Docs
  # -------------------------
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.18
    hooks:
    - id: pymarkdown
      files: ^(README\.md|docs/.*\.md)$
      exclude: ^(docs/.*/README\.md)$

  # -------------------------
  # Python
  # -------------------------
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.14
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
